/**
 * Unified exports for all type definitions
 */

// Agent types
export * from './agent.js';

// Command types
export * from './command.js';

// Trace types
export * from './trace.js';

// WebSocket message types
export * from './websocket.js';

// Protocol constants
export const PROTOCOL_VERSION = '0.1.0';

export const MESSAGE_TYPES = {
  // Agent to Server
  AGENT_CONNECT: 'AGENT_CONNECT',
  AGENT_HEARTBEAT: 'AGENT_HEARTBEAT',
  COMMAND_ACK: 'COMMAND_ACK',
  TERMINAL_OUTPUT: 'TERMINAL_OUTPUT',
  TRACE_EVENT: 'TRACE_EVENT',
  COMMAND_COMPLETE: 'COMMAND_COMPLETE',
  INVESTIGATION_REPORT: 'INVESTIGATION_REPORT',
  AGENT_ERROR: 'AGENT_ERROR',

  // Server to Agent
  COMMAND_REQUEST: 'COMMAND_REQUEST',
  COMMAND_CANCEL: 'COMMAND_CANCEL',
  AGENT_CONTROL: 'AGENT_CONTROL',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  SERVER_HEARTBEAT: 'SERVER_HEARTBEAT',

  // Server to Dashboard
  AGENT_STATUS: 'AGENT_STATUS',
  COMMAND_STATUS: 'COMMAND_STATUS',
  TERMINAL_STREAM: 'TERMINAL_STREAM',
  TRACE_UPDATE: 'TRACE_UPDATE',

  // Error
  ERROR: 'ERROR'
} as const;

export const ERROR_CODES = {
  AUTH_FAILED: 'AUTH_FAILED',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  RATE_LIMIT: 'RATE_LIMIT',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export const RATE_LIMITS = {
  AGENT_MESSAGES_PER_SECOND: 100,
  AGENT_MAX_PAYLOAD_SIZE: 1024 * 1024, // 1MB
  AGENT_MAX_CONCURRENT_COMMANDS: 5,
  DASHBOARD_MESSAGES_PER_SECOND: 50,
  DASHBOARD_MAX_SUBSCRIPTIONS: 20,
  DASHBOARD_MAX_PAYLOAD_SIZE: 512 * 1024 // 512KB
} as const;