#!/bin/bash

echo "=================================="
echo "RUN THIS COMMAND DIRECTLY IN YOUR TERMINAL:"
echo "=================================="
echo ""
echo "npx tsx src/cli.ts start --agent claude --auth-type subscription --interactive --no-websocket"
echo ""
echo "=================================="
echo ""
echo "The issue you're experiencing is that Claude is exiting immediately."
echo ""
echo "This appears to be because Claude is detecting something about the PTY"
echo "environment that makes it think it shouldn't run interactively."
echo ""
echo "For debugging, please also try this simple test command:"
echo "node test-claude-pty.js"
echo ""
echo "This test script successfully launches Claude with the UI."
echo ""